apiVersion: v1
kind: ServiceAccount
metadata:
  name: app1-dev-sa
  namespace: app1-dev
---
apiVersion: v1
kind: Secret
metadata:
  name: app1-dev-sa-secret
  namespace: app1-dev
  annotations:
    kubernetes.io/service-account.name: app1-dev-sa
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sa-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app1-stg-sa
  namespace: app1-stg