kind: Pod
apiVersion: v1
metadata:
  name: webapp
  namespace: app1-dev
spec:
  serviceAccountName: app1-dev-sa
  containers:
  - image: jweissig/app:0.0.1
    name: webapp
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "app1-dev-vault"