apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app1-dev-vault
  namespace: app1-dev
spec:
  provider: vault
  parameters:
    roleName: "default"
    objects: |
      - objectName: "secret1_key1"
        secretPath: "kv/assets/app1/app1-dev/secrets1"
        secretKey: "key1"
      - objectName: "secret1_key2"
        secretPath: "kv/assets/app1/app1-dev/secrets1"
        secretKey: "key2"
      - objectName: "secret2_key1"
        secretPath: "kv/assets/app1/app1-dev/secrets2"
        secretKey: "key1"
      - objectName: "secret2_key2"
        secretPath: "kv/assets/app1/app1-dev/secrets2"
        secretKey: "key2"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app1-stg-vault
  namespace: app1-stg
spec:
  provider: vault
  parameters:
    roleName: "default"
    objects: |
      - objectName: "secret1_key1"
        secretPath: "kv/assets/app1/app1-stg/secrets1"
        secretKey: "key1"
      - objectName: "secret1_key2"
        secretPath: "kv/assets/app1/app1-stg/secrets1"
        secretKey: "key2"
      - objectName: "secret2_key1"
        secretPath: "kv/assets/app1/app1-stg/secrets2"
        secretKey: "key1"
      - objectName: "secret2_key2"
        secretPath: "kv/assets/app1/app1-stg/secrets2"
        secretKey: "key2"
