kind: Pod
apiVersion: v1
metadata:
  name: webapp
  namespace: app1-dev
spec:
  serviceAccountName: app1-dev-sa
  containers:
  - image: nginx:1.25.5-alpine
    name: webapp
    resources:
      limits:
        memory: 128Mi
        cpu: "0.25"
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "app1-dev-vault"
---
kind: Pod
apiVersion: v1
metadata:
  name: webapp
  namespace: app1-stg
spec:
  serviceAccountName: app1-stg-sa
  containers:
  - image: nginx:1.25.5-alpine
    name: webapp
    resources:
      limits:
        memory: 128Mi
        cpu: "0.25"
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "app1-stg-vault"